baseURL = 'https://sdnpsaj.github.io/newsite/'
canonifyurls = true
languageCode = 'en-us'
publishDir = "docs"
title = '新闻首页'
theme = 'ananke'


[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
